services:
  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/carental
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    container_name: carental-mongo
    ports:
      - "27017:27017"